--Datos_Deuda
SELECT
    dbo.FACTURAS.ID_FAC,
    dbo.FACTURAS.COD_COM,
    dbo.FACTURAS.SUC_COM,
    dbo.FACTURAS.NUM_COM,
    dbo.FACTURAS.TIPO,
    dbo.FACTURAS.FECHA,
    dbo.FACTURAS.COD_SOC,
    dbo.FACTURAS.COD_PER,
    dbo.FACTURAS.COD_SUM,
    dbo.FACTURAS.VTO1,
    dbo.FACTURAS.TOTAL1,
    dbo.FACTURAS.VTO2,
    dbo.FACTURAS.TOTAL2,
    dbo.FACTURAS.PAGA,
    dbo.FACTURAS.FECHASALDO,
    dbo.FACTURAS.SALDO,
    dbo.FACTURAS.PERIODO,
    dbo.COMPROB.DEB_CRE,
    dbo.FACTURAS.ID_BLO,
    dbo.FACTURAS.CAE,
    dbo.FACTURAS.VTOCAE
FROM
    dbo.FACTURAS
    LEFT OUTER JOIN dbo.COMPROB ON dbo.FACTURAS.COD_COM = dbo.COMPROB.COD_COM 

--Datos_Personales
SELECT
    dbo.PERSONAS.TIP_PERSO,
    dbo.PERSONAS.COD_PER,
    dbo.PERSONAS.TIP_DNI,
    dbo.PERSONAS.NUM_DNI,
    dbo.PERSONAS.APELLIDOS,
    dbo.PERSONAS.SEXO,
    dbo.PERSONAS.CIVIL,
    dbo.PERSONAS.COD_CAL,
    dbo.CALLES.DES_CAL AS NOMBRECALLE,
    dbo.PERSONAS.NUMERO,
    dbo.PERSONAS.PISO,
    dbo.PERSONAS.DPTO,
    dbo.LOCALIDA.DES_LOC AS NOMBRELOCALIDAD,
    dbo.PERSONAS.FEC_NAC,
    dbo.PERSONAS.TELEFONO,
    dbo.PERSONAS.FAX,
    dbo.PERSONAS.COD_POS,
    dbo.PERSONAS.COD_PRO,
    dbo.PROVINC.DES_PRO AS PROVINCIA,
    dbo.PERSONAS.EMAIL,
    dbo.PERSONAS.GRU_SGR,
    dbo.PERSONAS.FAC_SGR,
    dbo.PERSONAS.DAD_SGR,
    dbo.PERSONAS.COD_SIT,
    dbo.SITIVA.DES_SIT AS DESCRI_SITIVA,
    dbo.PERSONAS.FEC_ALTA,
    dbo.SOCIOS.cod_soc,
    dbo.SOCIOS.cuit,
    dbo.SOCIOS.activo,
    dbo.SOCIOS.alta,
    dbo.SOCIOS.baja,
    dbo.SOCIOS.clave_web
FROM
    dbo.PERSONAS
    LEFT OUTER JOIN dbo.SOCIOS ON dbo.SOCIOS.cod_per = dbo.PERSONAS.COD_PER
    LEFT OUTER JOIN dbo.[DOCUMENT] ON dbo.[DOCUMENT].COD_DOC = dbo.PERSONAS.TIP_DNI
    LEFT OUTER JOIN dbo.EST_CIVIL ON dbo.EST_CIVIL.COD_CIVIL = dbo.PERSONAS.CIVIL
    LEFT OUTER JOIN dbo.CALLES ON dbo.CALLES.COD_CAL = dbo.PERSONAS.COD_CAL
    LEFT OUTER JOIN dbo.LOCALIDA ON dbo.LOCALIDA.COD_LOC = dbo.PERSONAS.COD_LOC
    LEFT OUTER JOIN dbo.PROVINC ON dbo.PROVINC.COD_PRO = dbo.PERSONAS.COD_PRO
    LEFT OUTER JOIN dbo.SITIVA ON dbo.SITIVA.COD_SIT = dbo.PERSONAS.COD_SIT
    
 --Datos_ServiciosXSuministro
SELECT
    dbo.SERSOC.ID_SERSOC,
    dbo.SERSOC.COD_SUM,
    dbo.SERSOC.COD_SER,
    dbo.SERSOC.COD_CAT,
    dbo.SERSOC.COD_CATSER,
    dbo.CATE_SER.DES_CAT AS NOMBRE_CATEGORIA,
    dbo.SERSOC.FEC_ALTA,
    dbo.SERSOC.FEC_BAJA,
    dbo.SERSOC.NUM_MED AS [NUM_MED/NUMTEL],
    dbo.SERSOC.COD_CAL,
    dbo.CALLES.DES_CAL AS NOMBRECALLE,
    dbo.SERSOC.NUMERO,
    dbo.SERSOC.PISO,
    dbo.SERSOC.DPTO,
    dbo.SERSOC.COD_LOC,
    dbo.LOCALIDA.DES_LOC AS NOMBRELOCALIDAD,
    dbo.SERSOC.COD_POS,
    dbo.SERSOC.CAT_CIR,
    dbo.SERSOC.CAT_LOT,
    dbo.SERSOC.CAT_MAN,
    dbo.SERSOC.CAT_PAR,
    dbo.SERSOC.CAT_PH,
    dbo.SERSOC.GUIA,
    dbo.SERSOC.NOM_GUIA,
    dbo.SERSOC.COD_PRO,
    dbo.PROVINC.DES_PRO AS PROVINCIA,
    dbo.SERSOC.ALTA_ADM,
    dbo.SERSOC.BAJA_ADM,
    dbo.SERSOC.NRO_CERT,
    dbo.SERSOC.COD_PROF,
    dbo.SERSOC.VTO_CERT
FROM
    dbo.SERSOC
    LEFT OUTER JOIN dbo.SERVICIO ON dbo.SERVICIO.COD_SER = dbo.SERSOC.COD_SER
    LEFT OUTER JOIN dbo.CATE_SER ON dbo.SERSOC.COD_CAT = dbo.CATE_SER.COD_CAT
    AND dbo.SERSOC.COD_SER = dbo.CATE_SER.COD_SER
    LEFT OUTER JOIN dbo.CALLES ON dbo.CALLES.COD_CAL = dbo.SERSOC.COD_CAL
    LEFT OUTER JOIN dbo.LOCALIDA ON dbo.LOCALIDA.COD_LOC = dbo.SERSOC.COD_LOC
    LEFT OUTER JOIN dbo.PROVINC ON dbo.SERSOC.COD_PRO = dbo.PROVINC.COD_PRO
    LEFT OUTER JOIN dbo.PROFESIO ON dbo.PROFESIO.COD_PROF = dbo.SERSOC.COD_PROF
    
 --Datos_Suministro
SELECT
    dbo.SUMSOC.cod_sum,
    dbo.SUMSOC.cod_soc,
    dbo.SUMSOC.cod_sit,
    dbo.SITIVA.DES_SIT AS DESCRI_SITIVA,
    dbo.CALLES.COD_CAL,
    dbo.CALLES.DES_CAL AS NOMBRECALLE,
    dbo.SUMSOC.numero,
    dbo.SUMSOC.piso,
    dbo.SUMSOC.dpto,
    dbo.SUMSOC.cod_loc,
    dbo.LOCALIDA.DES_LOC AS NOMBRELOCALIDAD,
    dbo.SUMSOC.cod_pos,
    dbo.SUMSOC.nof_sum,
    dbo.SUMSOC.email,
    dbo.SUMSOC.telefono,
    dbo.SUMSOC.facturae,
    dbo.SUMSOC.movil,
    dbo.SUMSOC.alta_adm,
    dbo.SUMSOC.cod_sib,
    dbo.SUMSOC.cod_pro,
    dbo.PROVINC.DES_PRO AS PROVINCIA
FROM
    dbo.SUMSOC
    LEFT OUTER JOIN dbo.SITIVA ON dbo.SITIVA.COD_SIT = dbo.SUMSOC.cod_sit
    LEFT OUTER JOIN dbo.CALLES ON dbo.CALLES.COD_CAL = dbo.SUMSOC.cod_cal
    LEFT OUTER JOIN dbo.LOCALIDA ON dbo.LOCALIDA.COD_LOC = dbo.SUMSOC.cod_loc
    LEFT OUTER JOIN dbo.PROVINC ON dbo.PROVINC.COD_PRO = dbo.SUMSOC.cod_pro
    LEFT OUTER JOIN dbo.SITIBR ON dbo.SITIBR.COD_SIT = dbo.SUMSOC.cod_sib